--- 
javascripts: 
- base: 
  - builder
  - effects
  - controls
  - control_extensions
  - in_place_completer
  - lightbox
  - validation_cn
  - text_field_default_value
  - ratings_component
  - niftycube
  - fabtabulous
  - dynamic_popmenu  
  - application
- prototype-ui:
  - prototype-ui
- dragdrop:
  - dragdrop
- swfupload:
  - swfupload
stylesheets: 
- base:
  - blueprint/screen
  - blueprint/plugins/buttons/screen
  - dynamic_popmenu
  - lightbox
  - niftyCorners
  - ratings
  - style_min
  - tabs
  - applicationStyleSheet
  - auto_complete_like_facebook
  
