# Outgoing email settings

production:
  delivery_method: :smtp
  smtp_settings:
    address: smtp.21cn.com
    port: 25
    domain: www.21cn.com
    authentication: :login
    user_name: zhangming321
    password: zmil
  
development:
  delivery_method: :smtp
  smtp_settings:
    address: smtp.21cn.com
    port: 25
    domain: www.21cn.com
    authentication: :login
    user_name: zhangming321
    password: zmil
