# Outgoing email settings

development:
  delivery_method: :test
  smtp_settings:
    address: www.shuikaopu.com
    port: 25
    domain: shuikaopu.com
    authentication: :login
    user_name: no-reply
    password: wangchen
  
production:
  delivery_method: :smtp
  smtp_settings:
    address: www.shuikaopu.com
    port: 25
    domain: shuikaopu.com
    authentication: :login
    user_name: no-reply
    password: wangchen
