# Outgoing email settings

development:
  delivery_method: :smtp
  smtp_settings:
    address: smtp.163.com
    port: 25
    domain: 163.com
    authentication: :login
    user_name: tomorrownull@163.com
    password: mingtian
  
production:
  delivery_method: :smtp
  smtp_settings:
    address: smtp.21cn.com
    port: 25
    domain: www.21cn.com
    authentication: :login
    user_name: zhangming321
    password: zmil
