# Here you can specify default options for TinyMCE across all controllers
#
 theme: advanced
 theme_advanced_toolbar_location: "top"
 theme_advanced_buttons1: "bold,italic,underline,formatselect"
 theme_advanced_buttons2: ""
 theme_advanced_buttons3: ""
 theme_advanced_toolbar_align: "left"
 language : 'zh-cn'
# plugins:
#  - table
#  - fullscreen
